// ─── Phase 13.1.6 — Firebase production placeholders ────────────────────────
//
// This file is REGENERATED by `flutterfire configure`. Until that one-time
// setup runs against the real `tezketkaz-prod` Firebase project, every value
// below is a STUB:
//
//   • In DEBUG mode → `Firebase.initializeApp()` simply fails; the app
//     swallows the error in `services/firebase_setup.dart` and keeps booting
//     without push notifications.
//   • In RELEASE mode → we deliberately THROW so an unconfigured production
//     binary cannot ship. The check below short-circuits before any FCM call
//     is made.
//
// See `docs/runbooks/firebase-prod-setup.md` for the activation runbook.
// ────────────────────────────────────────────────────────────────────────────

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kDebugMode, kIsWeb, kReleaseMode, TargetPlatform, debugPrint;

/// Marker string baked into every stub field. When [DefaultFirebaseOptions]
/// detects this in release mode it refuses to return options.
const String _kStubProjectId = 'STUB_PROJECT';

class DefaultFirebaseOptions {
  /// Returns the platform-appropriate [FirebaseOptions].
  ///
  /// Behaviour by build mode when the placeholders have not been replaced:
  /// * **release** — throws [StateError] so a misconfigured prod binary cannot
  ///   silently run with stub credentials.
  /// * **debug**   — prints a one-line warning and returns the stubs anyway;
  ///   `Firebase.initializeApp()` then fails harmlessly and the wrapper in
  ///   `services/firebase_setup.dart` logs + degrades.
  static FirebaseOptions get currentPlatform {
    final opts = _rawOptions();
    if (opts.projectId == _kStubProjectId) {
      if (kReleaseMode) {
        throw StateError(
          'Firebase is not configured for production. Run `flutterfire '
          'configure --project=tezketkaz-prod` and rebuild. '
          'See docs/runbooks/firebase-prod-setup.md.',
        );
      }
      if (kDebugMode) {
        debugPrint(
          '[firebase_options] Using STUB credentials — push notifications '
          'will not work. Run `flutterfire configure` to activate.',
        );
      }
    }
    return opts;
  }

  static FirebaseOptions _rawOptions() {
    if (kIsWeb) return _web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _android;
      case TargetPlatform.iOS:
        return _ios;
      default:
        throw UnsupportedError(
          'Firebase not configured for ${defaultTargetPlatform.name}. '
          'Run `flutterfire configure` and add the platform.',
        );
    }
  }

  // ── STUB placeholders ─────────────────────────────────────────────────────
  // TODO(flutterfire): replace via `flutterfire configure --project=tezketkaz-prod`.
  static const _web = FirebaseOptions(
    apiKey: 'STUB_API_KEY',
    appId: '1:000000000000:web:stub',
    messagingSenderId: '000000000000',
    projectId: _kStubProjectId,
    authDomain: '$_kStubProjectId.firebaseapp.com',
  );

  // TODO(flutterfire): Android — replace via `flutterfire configure`.
  static const _android = FirebaseOptions(
    apiKey: 'STUB_API_KEY',
    appId: '1:000000000000:android:stub',
    messagingSenderId: '000000000000',
    projectId: _kStubProjectId,
  );

  // TODO(flutterfire): iOS — replace via `flutterfire configure`.
  static const _ios = FirebaseOptions(
    apiKey: 'STUB_API_KEY',
    appId: '1:000000000000:ios:stub',
    messagingSenderId: '000000000000',
    projectId: _kStubProjectId,
    iosBundleId: 'uz.tezketkaz.app',
  );
}
